# This workflow concerns the preparation of the `changeset` PR and keeping it updated by tracking the changes on `main` branch.
name: Create Release PR

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  create-release-pr:
    name: Create Release PR
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Check if a branch is whitelisted and maintained
        id: branch-check
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          WHITELISTED_BRANCHES=("main" "releases/*")

          IS_WHITELISTED=false
          # Check the branch against the whitelist using wildcard matching
          for BRANCH in "${WHITELISTED_BRANCHES[@]}"; do
            if [[ "$BRANCH_NAME" == $BRANCH ]]; then
              IS_WHITELISTED=true;
              break;
            fi
          done

          if [ "$IS_WHITELISTED" == true ]; then
            echo "Branch is whitelisted: $BRANCH_NAME"
          else
            echo "Branch $BRANCH_NAME is not whitelisted."
            exit 1
          fi

          echo "branch_name=${BRANCH_NAME}" >> "$GITHUB_OUTPUT"

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ steps.branch-check.outputs.branch_name }}

      - name: Check for changeset files
        run: |
          if ! ls .changeset/*.md | grep -q '\.changeset\/[a-z-]\+\.md$'; then
            echo "No changeset files found. Exiting workflow."
            exit 1
          fi

          echo "Changeset files found. Continuing with the workflow."

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          install-nodejs: 'true'

      # Keep the version of the PRs up-to-date
      - name: Create Release Pull Request
        id: release-pr
        uses: changesets/action@aba318e9165b45b7948c60273e0b72fce0a64eb9 # v1.4.7
        with:
          # This branch context is ignored in this step: https://github.com/changesets/action/blob/50750fa876cc1e54c7cb972db5e2f7271fc53d99/src/run.ts#L328, therefore the usage of `branch`
          branch: ${{ steps.branch-check.outputs.branch_name }}
          title: 'chore(release): bump version and update changelog'
          commit: 'chore(release): bump version and update changelog'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
