# This workflow concerns the preparation of the `changeset` PR and keeping it updated by tracking the changes on `main` branch.
name: Pre-Release Preparation

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pre-release:
    name: Pre-Release Preparation
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check for changeset files and 'pre-release' label exist
        id: check-conditions
        run: |
          if ls .changeset/*.md | grep '\.changeset\/[a-z-]\+\.md$'; then
            echo "has_changeset=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_changeset=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          install-nodejs: 'true'

      # Keep the version of the PRs up-to-date
      - name: Create Release Pull Request
        id: release-pr
        if: ${{ steps.check-conditions.outputs.has_changeset == 'true' }}
        uses: changesets/action@aba318e9165b45b7948c60273e0b72fce0a64eb9 #v1.4.7
        with:
          branch: 'main'
          title: 'chore(release): bump version and update changelog'
          commit: 'chore(release): bump version and update changelog'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
