name: 'Publish Bytecode'

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-bytecode:
    strategy:
      matrix:
        node-version:
          - 18.x
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Flatten contracts
        run: npm run flatten

      - name: Clean artifacts
        run: npm run clean:artifacts

      - name: Get release tag
        run: echo "release_tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: show release tag
        run: echo "${release_tag}"

      - name: Create zip file
        working-directory: ./artifacts
        run: |
          zip -r Bytecode-${release_tag}.zip *

      # - name: Upload Bytecode to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: ./artifacts/Bytecode-${release_tag}.zip
      #     tag: ${release_tag}
      #     overwrite: true
